const Data = [
    {
        "experience" :  10,
        "doctorName":"Dr. Ramesh Patil",
        "speciality":"Ayurveda",
        "rating":4.7,
        "clinicName":"Ayushman Bhava Ayurveda & Keraliya Panchkarma Clinic",
        "price" :750,
        "feedbackNumber":778,
        "areaNearby": 3.1,
        "area":"Fashion Street",
        "city":"Mumbai",
        "gender" : "male"
    },
    {
        "experience" :  15,
        "doctorName":"Dr. Sunil Deshmukh",
        "speciality":"Dentist",
        "rating":4.1,
        "clinicName":"Deshmukh Clinic",
        "price" :350,
        "feedbackNumber":438,
        "areaNearby": 8.3,
        "area":"Katraj",
        "city":"Pune",
        "gender" : "male"
    },
    {
        "experience" :  25,
        "doctorName":"Dr. Swapnil Krishnakant Katre",
        "speciality":"Dermatologist",
        "rating":3.7,
        "clinicName":"Suddata Clinic",
        "price" :550,
        "feedbackNumber":778,
        "areaNearby": 3.1,
        "area":"Kothrud",
        "city":"Pune",
        "gender" : "male"
    },
    {
        "experience" :  5,
        "doctorName":"Dr. Rishi Rajput",
        "speciality":"ENT",
        "rating":4.3,
        "clinicName":" Rajput ENT Clinic",
        "price" :350,
        "feedbackNumber":278,
        "areaNearby": 1.1,
        "area":"Karve Nagar",
        "city":"Pune",
        "gender" : "male"
    },
    {
        "experience" :  10,
        "doctorName":"Dr. Kundan Sanjay Kabra",
        "speciality":"General Physician",
        "rating":4.9,
        "clinicName":"Kundan Clinic",
        "price" :1050,
        "feedbackNumber":1078,
        "areaNearby": 5.1,
        "area":"Sahyadri Nagar",
        "city":"Pune",
        "gender" : "male"
    },
    {
        "experience" :  10,
        "doctorName":"Dr. Natrajan Iyyer",
        "speciality":"Ayurveda",
        "rating":4.7,
        "clinicName":"Ayushman Bhava Ayurveda & Keraliya Panchkarma Clinic",
        "price" :750,
        "feedbackNumber":778,
        "areaNearby": 3.1,
        "area":"Gunjal Baba Nagar",
        "city":"Bangalore",
        "gender" : "male"
    },
    {
        "experience" :  10,
        "doctorName":"Dr. Swapnil Katre",
        "speciality":"Ayurveda",
        "rating":4.7,
        "clinicName":"Ayushman Bhava Ayurveda & Keraliya Panchkarma Clinic",
        "price" :750,
        "feedbackNumber":778,
        "areaNearby": 3.1,
        "area":"Kondhwa",
        "city":"Pune",
        "gender" : "male"
    },
    {
        "experience" :  5,
        "doctorName":"Dr. Swati Kulkarni",
        "speciality":"Dermatologist",
        "rating":2.7,
        "clinicName":"Kulkarni Clinic",
        "price" :950,
        "feedbackNumber":278,
        "areaNearby": 2.1,
        "area":"Hamilton Square",
        "city":"Chennai",
        "gender" : "female"
    },
    {
        "experience" :  10,
        "doctorName":"Dr. Swapnil Katre",
        "speciality":"Ayurveda",
        "rating":4.7,
        "clinicName":"Ayushman Bhava Ayurveda & Keraliya Panchkarma Clinic",
        "price" :750,
        "feedbackNumber":778,
        "areaNearby": 3.1,
        "area":"Gunjal Baba Nagar",
        "city":"Pune",
        "gender" : "male"
    },
    {
        "experience" :  19,
        "doctorName":"Dr. Divya Chaturvedi",
        "speciality":"Ayurveda",
        "rating":4.3,
        "clinicName":"Keraliya Panchkarma Clinic",
        "price" :550,
        "feedbackNumber":878,
        "areaNearby": 6.1,
        "area":"Cannaught Garden",
        "city":"Pune",
        "gender" : "female"
    },
    {
        "experience" :  29,
        "doctorName":"Dr. Maya Chaturvedi",
        "speciality":"Ayurveda",
        "rating":4.3,
        "clinicName":"Keraliya Panchkarma Clinic",
        "price" :550,
        "feedbackNumber":878,
        "areaNearby": 6.1,
        "area":"Cannaught Garden",
        "city":"Pune",
        "gender" : "female"
    },
    {
        "experience" :  29,
        "doctorName":"Dr. Maya Chaturvedi",
        "speciality":"Ayurveda",
        "rating":4.3,
        "clinicName":"Keraliya Panchkarma Clinic",
        "price" :550,
        "feedbackNumber":878,
        "areaNearby": 6.1,
        "area":"Cannaught Garden",
        "city":"Pune",
        "gender" : "female"
    } ,
    {
        "experience" :  29,
        "doctorName":"Dr. Maya Chaturvedi",
        "speciality":"Ayurveda",
        "rating":4.3,
        "clinicName":"Keraliya Panchkarma Clinic",
        "price" :550,
        "feedbackNumber":878,
        "areaNearby": 6.1,
        "area":"Cannaught Garden",
        "city":"Pune",
        "gender" : "female"
    }  ,
    {
        "experience" :  29,
        "doctorName":"Dr. Maya Chaturvedi",
        "speciality":"Ayurveda",
        "rating":4.3,
        "clinicName":"Keraliya Panchkarma Clinic",
        "price" :550,
        "feedbackNumber":878,
        "areaNearby": 6.1,
        "area":"Cannaught Garden",
        "city":"Pune",
        "gender" : "female"
    },
    {
        "experience" :  29,
        "doctorName":"Dr. Maya Chaturvedi",
        "speciality":"Ayurveda",
        "rating":4.3,
        "clinicName":"Keraliya Panchkarma Clinic",
        "price" :550,
        "feedbackNumber":878,
        "areaNearby": 6.1,
        "area":"Cannaught Garden",
        "city":"Pune",
        "gender" : "female"
    },
    {
        "experience" :  29,
        "doctorName":"Dr. Maya Chaturvedi",
        "speciality":"Ayurveda",
        "rating":4.3,
        "clinicName":"Keraliya Panchkarma Clinic",
        "price" :550,
        "feedbackNumber":878,
        "areaNearby": 6.1,
        "area":"Cannaught Garden",
        "city":"Pune",
        "gender" : "female"
    },
    {
        "experience" :  29,
        "doctorName":"Dr. Maya Chaturvedi",
        "speciality":"Ayurveda",
        "rating":4.3,
        "clinicName":"Keraliya Panchkarma Clinic",
        "price" :550,
        "feedbackNumber":878,
        "areaNearby": 6.1,
        "area":"Cannaught Garden",
        "city":"Pune",
        "gender" : "female"
    }             
];

export default Data;